spring:
  datasource:
    url: jdbc:mysql://root:CUVpsVhXWDldSxdxmeQLvGCfiIJgxRvK@yamanote.proxy.rlwy.net:24125/railway
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  docker:
    compose:
      enabled: false
      file: ./src/main/docker/compose/docker-compose.yaml
      skip:
        in-tests: false
      lifecycle:
        stop-command: down
api:
  endpoint:
    base-url: /api/v1
server:
  port: 8080
