spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sencare_db
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:sa12345}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  docker:
    compose:
      enabled: false
      file: ./src/main/docker/compose/docker-compose.yaml
      skip:
        in-tests: false
      lifecycle:
        stop-command: down
api:
  endpoint:
    base-url: /api/v1
